<?php

use Illuminate\Database\Seeder;

use Carbon\Carbon;

class SchoolEditorsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if (!App::environment('production')) {
            DB::table('school_editors')->insert([
                [
                    'username' => 'editor1',
                    'school_code' => '01',
                    'organization' => '註冊組',
                    'has_admin' => true,
                    'created_at' => Carbon::now()->toIso8601String(),
                    'updated_at' => Carbon::now()->toIso8601String()
                ],

                [
                    'username' => 'editor2',
                    'school_code' => '02',
                    'organization' => '註冊組',
                    'has_admin' => true,
                    'created_at' => Carbon::now()->toIso8601String(),
                    'updated_at' => Carbon::now()->toIso8601String()],
                [
                    'username' => 'editor3',
                    'school_code' => '04',
                    'organization' => '註冊組',
                    'has_admin' => true,
                    'created_at' => Carbon::now()->toIso8601String(),
                    'updated_at' => Carbon::now()->toIso8601String()
                ]
            ]);
        }

        DB::table('school_editors')->insert([
            ['school_code' => '00','username' => 'ntu00','organization' => '註冊組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '01','username' => 'ntu','organization' => '註冊組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '02','username' => 'ncku','organization' => '國際事務處僑生與陸生事務組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '03','username' => 'ncyu','organization' => '國際事務處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '04','username' => 'ncnu','organization' => '教務處招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '05','username' => 'nchu','organization' => '教務處招生暨資訊組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '06','username' => 'ccu','organization' => '教務處招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '07','username' => 'ntnu','organization' => '國際事務處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '08','username' => 'ndhu','organization' => '國際事務處國際宣傳與招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '09','username' => 'ntou','organization' => '國際學生事務組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '10','username' => 'ntpu','organization' => '教務處綜合業務組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '11','username' => 'nctu','organization' => '教務處綜合組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '12','username' => 'nuk','organization' => '教務處招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '13','username' => 'nccu','organization' => '教務處綜合業務組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '14','username' => 'niu','organization' => '國際事務中心','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '15','username' => 'ncu','organization' => '教務處招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '16','username' => 'nuu','organization' => '綜合業務組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '17','username' => 'nthu','organization' => '教務處招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '18','username' => 'nutn','organization' => '教務處企劃組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '19','username' => 'nsysu','organization' => '教務處招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '20','username' => 'nttu','organization' => '教務處綜合業務組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '21','username' => 'ym','organization' => '綜合業務組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '22','username' => 'ndmctsgh','organization' => '教務處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '23','username' => 'ncue','organization' => '教務處教學資源組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '24','username' => 'npue','organization' => '教務處綜合業務組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '25','username' => 'tmue','organization' => '教務處招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '26','username' => 'ntcu','organization' => '國際及兩岸事務暨研究發展處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '27','username' => 'nknu','organization' => '教務處註冊組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '28','username' => 'ntue','organization' => '教務處註冊組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '29','username' => 'nhcue','organization' => '註冊組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '30','username' => 'ntupes','organization' => '招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '31','username' => 'tpec','organization' => '教務處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '32','username' => 'ntsu','organization' => '教務處註冊組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '33','username' => 'tnua','organization' => '教務處招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '34','username' => 'ntua','organization' => '教務處綜合業務組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '35','username' => 'tnnua','organization' => '教務處註冊組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '36','username' => 'pccu','organization' => '教務處招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '37','username' => 'tku','organization' => '招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '38','username' => 'mcu','organization' => '教務處綜合業務組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '39','username' => 'thu','organization' => '招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '40','username' => 'usc','organization' => '教務處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '41','username' => 'isu','organization' => '招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '42','username' => 'pu','organization' => '國際暨兩岸事務處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '43','username' => 'au','organization' => '招生中心','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '44','username' => 'fcu','organization' => '招生行政組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '45','username' => 'fju','organization' => '教務處招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '46','username' => 'cjcu','organization' => '入學服務處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '47','username' => 'asia','organization' => '國際學院','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '48','username' => 'shu','organization' => '教務處招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '49','username' => 'dyu','organization' => '國際暨兩岸交流處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '50','username' => 'chu','organization' => '教務處 註冊組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '51','username' => 'tsu','organization' => '國際及兩岸事務處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '52','username' => 'ukn','organization' => '教務處招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '53','username' => 'ctbc','organization' => '教務處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '54','username' => 'mdu','organization' => '國際事務處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '55','username' => 'scu','organization' => '招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '56','username' => 'knu','organization' => '招生事務處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '57','username' => 'yzu','organization' => '教務處註冊組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '58','username' => 'toko','organization' => '招生處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '59','username' => 'hcu','organization' => '招生服務處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '60','username' => 'nhu','organization' => '國際及兩岸交流處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '61','username' => 'cycu','organization' => '國際暨兩岸教育處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '62','username' => 'hfu','organization' => '教務處招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '63','username' => 'ttu','organization' => '註冊組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '64','username' => 'fgu','organization' => '國際暨兩岸事務處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '65','username' => 'cgu','organization' => '教務處招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '66','username' => 'csmu','organization' => '教務處招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '67','username' => 'kmu','organization' => '教務處 招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '68','username' => 'cmu','organization' => '公共事務處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '69','username' => 'tmu','organization' => '教務處招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '70','username' => 'tcu','organization' => '教務處註冊組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '71','username' => 'ntust','organization' => '教務處註冊組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '72','username' => 'yuntech','organization' => '教務處綜合業務組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '73','username' => 'ntut','organization' => '國際事務處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '74','username' => 'npust','organization' => '綜合業務組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '75','username' => 'nkfust','organization' => '國際處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '76','username' => 'kuas','organization' => '招生業務組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '77','username' => 'nkmu','organization' => '研究發展處國際事務組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '78','username' => 'nfu','organization' => '綜合教務組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '79','username' => 'npic','organization' => '招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '80','username' => 'nqu','organization' => '研發處國際暨兩岸事務中心','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '81','username' => 'ncut','organization' => '教務處綜合業務組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '82','username' => 'nutc','organization' => '國際事務處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '83','username' => 'nkuht','organization' => '教務處綜合業務組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '84','username' => 'ntub','organization' => '教務處企劃組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '85','username' => 'ntunhs','organization' => '研發處國際暨兩岸教育中心','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '86','username' => 'cyut','organization' => '教務處招生服務中心','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '87','username' => 'stust','organization' => '教務處綜合業務組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '88','username' => 'ksu','organization' => '教務處綜合業務組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '89','username' => 'stu','organization' => '教務處教務組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '90','username' => 'cnu','organization' => '教務處招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '91','username' => 'must','organization' => '國際交流中心','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '92','username' => 'fy','organization' => '教務處招生暨入學服務中心','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '93','username' => 'hk','organization' => '國際暨兩岸事務處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '94','username' => 'csu','organization' => '國際事務處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '95','username' => 'uch','organization' => '招生處試務組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '96','username' => 'vnu','organization' => '教務處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '97','username' => 'mcut','organization' => '註冊組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '98','username' => 'cute','organization' => '教務行政組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '99','username' => 'tajen','organization' => '國際暨兩岸事務處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'A0','username' => 'kyu','organization' => '研發處國際交流中心','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'A1','username' => 'ltu','organization' => '教務處註冊組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'A2','username' => 'sju','organization' => '國際學術交流中心','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'A3','username' => 'ctust','organization' => '招生及國際合作中心','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'A4','username' => 'tut','organization' => '招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'A5','username' => 'feu','organization' => '教務處註冊組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'A6','username' => 'ypu','organization' => '教務處註冊組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'A7','username' => 'ccut','organization' => '招生事務中心','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'A8','username' => 'nkut','organization' => '秘書室國際交流暨兩岸事務中心','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'A9','username' => 'cust','organization' => '教務處註冊組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'B0','username' => 'tust','organization' => '國際交流中心','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'B1','username' => 'dahan','organization' => '教務處招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'B2','username' => 'wzu','organization' => '國際暨兩岸合作處境外學生事務組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'B3','username' => 'just','organization' => '教務處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'B4','username' => 'tcust','organization' => '教務處招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'B5','username' => 'ytit','organization' => '國際事務中心','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'B6','username' => 'fotech','organization' => '教務處招生中心','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'B7','username' => 'oit','organization' => '教務處註冊組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'B8','username' => 'tpcu','organization' => '國際交流中心','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'B9','username' => 'nanya','organization' => '教務處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'C0','username' => 'wfu','organization' => '國際暨兩岸事務中心','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'C1','username' => 'tnu','organization' => '國際交流中心','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'C2','username' => 'ocu','organization' => '教務處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'C3','username' => 'chihlee','organization' => '國際暨兩岸交流處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'C4','username' => 'hwu','organization' => '教務處註冊組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'C5','username' => 'takming','organization' => '教務處綜合業務組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'C6','username' => 'twu','organization' => '國際暨兩岸事務處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'C7','username' => 'meiho','organization' => '國際及兩岸交流處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'C8','username' => 'dlit','organization' => '教務處註冊組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'C9','username' => 'nju','organization' => '招生處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'D0','username' => 'tf','organization' => '研究發展處國際暨兩岸交流組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'D1','username' => 'hust','organization' => '招生服務中心','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'D2','username' => 'cku','organization' => '研發處國際合作暨兩岸交流組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'D3','username' => 'hwh','organization' => '研發處國際交流中心','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'D4','username' => 'tht','organization' => '招生事務中心','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'D5','username' => 'tcmt','organization' => '招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'D6','username' => 'dila','organization' => '教務組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'D7','username' => 'npu','organization' => '教務處註冊組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'D8','username' => 'lhu','organization' => '國際暨兩岸合作處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'D9','username' => 'ctu','organization' => '國際合作與交流處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'E0','username' => 'utaipei','organization' => '教務處招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'E1','username' => 'hwai','organization' => '國際交流組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'E2','username' => 'ydu','organization' => '國際合作處國際與兩岸合作交流中心','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'E3','username' => 'fit','organization' => '教務處註冊課務組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'E4','username' => 'lit','organization' => '招生中心','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'E5','username' => 'cgust','organization' => '教務處註冊組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'E6','username' => 'cit','organization' => '國際暨兩岸事務處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'E7','username' => 'ttc','organization' => '學生發展處招生中心','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'E8','username' => 'apic','organization' => '永續發展處招生中心','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'E9','username' => 'kfcdc','organization' => '教務處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'F0','username' => 'nptu','organization' => '國際事務處-國際學生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'F1','username' => 'mmc','organization' => '教務處招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'F2','username' => 'tcpa','organization' => '教務處註冊組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'F3','username' => 'tbts','organization' => '祕書暨公關室','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'F4','username' => 'cct','organization' => '教務處註冊組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'F5','username' => 'iktc','organization' => '教務處','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'FF','username' => 'nups','organization' => '僑先部招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'HW','username' => 'overseas','organization' => '招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'HW','username' => 'overseas.ncnu','organization' => '招生組','has_admin' => true,'created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
        ]);
    }
}
