<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class SchoolLastYearSelfEnrollmentAndFiveYearStatusTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('school_last_year_self_enrollment_and_five_year_status')->insert([
            ['school_code' => '01','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '02','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '03','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '04','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '05','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '06','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '07','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '08','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '09','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '10','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '11','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '12','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '13','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '14','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '15','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '16','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '17','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '18','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '19','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '20','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '21','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '22','has_five_year_student_allowed' => false,'has_self_enrollment' => false],
            ['school_code' => '23','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '24','has_five_year_student_allowed' => false,'has_self_enrollment' => false],
            ['school_code' => '25','has_five_year_student_allowed' => false,'has_self_enrollment' => false],
            ['school_code' => '26','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '27','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '28','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '29','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '30','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '31','has_five_year_student_allowed' => false,'has_self_enrollment' => false],
            ['school_code' => '32','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '33','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '34','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '35','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '36','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '37','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '38','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '39','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '40','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '41','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '42','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '43','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '44','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '45','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '46','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '47','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '48','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '49','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '50','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '51','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '52','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '53','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '54','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '55','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '56','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '57','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '58','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '59','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '60','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '61','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '62','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '63','has_five_year_student_allowed' => false,'has_self_enrollment' => true],
            ['school_code' => '64','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '65','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '66','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '67','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '68','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '69','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '70','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '71','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '72','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '73','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '74','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '75','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '76','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '77','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '78','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '79','has_five_year_student_allowed' => false,'has_self_enrollment' => false],
            ['school_code' => '80','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '81','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '82','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '83','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '84','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '85','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '86','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '87','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '88','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '89','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '90','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '91','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '92','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '93','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '94','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '95','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '96','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => '97','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '98','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => '99','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => 'A0','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => 'A1','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => 'A2','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => 'A3','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => 'A4','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => 'A5','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => 'A6','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => 'A7','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => 'A8','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => 'A9','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => 'B0','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => 'B1','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => 'B2','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => 'B3','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => 'B4','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => 'B5','has_five_year_student_allowed' => false,'has_self_enrollment' => false],
            ['school_code' => 'B6','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => 'B7','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => 'B8','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => 'B9','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => 'C0','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => 'C1','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => 'C2','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => 'C3','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => 'C4','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => 'C5','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => 'C6','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => 'C7','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => 'C8','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => 'C9','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => 'D0','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => 'D1','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => 'D2','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => 'D3','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => 'D4','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => 'D5','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => 'D6','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => 'D7','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => 'D8','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => 'D9','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => 'E0','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => 'E1','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => 'E2','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => 'E3','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => 'E4','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => 'E5','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => 'E6','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => 'E7','has_five_year_student_allowed' => false,'has_self_enrollment' => false],
            ['school_code' => 'E8','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => 'E9','has_five_year_student_allowed' => false,'has_self_enrollment' => false],
            ['school_code' => 'F0','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => 'F1','has_five_year_student_allowed' => false,'has_self_enrollment' => false],
            ['school_code' => 'F2','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
            ['school_code' => 'F3','has_five_year_student_allowed' => false,'has_self_enrollment' => false],
            ['school_code' => 'F4','has_five_year_student_allowed' => true,'has_self_enrollment' => true],
            ['school_code' => 'F5','has_five_year_student_allowed' => false,'has_self_enrollment' => false],
            ['school_code' => 'F6','has_five_year_student_allowed' => false,'has_self_enrollment' => false],
            ['school_code' => 'F7','has_five_year_student_allowed' => false,'has_self_enrollment' => false],
            ['school_code' => 'FF','has_five_year_student_allowed' => true,'has_self_enrollment' => false],
        ]);
    }
}
