<?php

use Illuminate\Database\Seeder;

use Carbon\Carbon;

class SchoolEditorsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if (!App::environment('production')) {
            DB::table('school_editors')->insert([
                [
                    'username' => 'editor1',
                    'school_code' => '01',
                    'organization' => '註冊組',
                    'has_admin' => true,
                    'created_at' => Carbon::now()->toIso8601String(),
                    'updated_at' => Carbon::now()->toIso8601String()
                ],

                [
                    'username' => 'editor2',
                    'school_code' => '02',
                    'organization' => '註冊組',
                    'has_admin' => true,
                    'created_at' => Carbon::now()->toIso8601String(),
                    'updated_at' => Carbon::now()->toIso8601String()],
                [
                    'username' => 'editor3',
                    'school_code' => '04',
                    'organization' => '註冊組',
                    'has_admin' => true,
                    'created_at' => Carbon::now()->toIso8601String(),
                    'updated_at' => Carbon::now()->toIso8601String()
                ]
            ]);
        }

        DB::table('school_editors')->insert([
            ['school_code' => '01','has_admin' => true,'username' => '2017ntu01','organization' => '註冊組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '02','has_admin' => true,'username' => '2017ncku02','organization' => '國際事務處僑生與陸生事務組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '03','has_admin' => true,'username' => '2017ncyu03','organization' => '國際事務處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '04','has_admin' => true,'username' => '2017ncnu04','organization' => '教務處招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '05','has_admin' => true,'username' => '2017nchu05','organization' => '教務處招生暨資訊組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '06','has_admin' => true,'username' => '2017ccu06','organization' => '教務處招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '07','has_admin' => true,'username' => '2017ntnu07','organization' => '國際事務處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '08','has_admin' => true,'username' => '2017ndhu08','organization' => '國際事務處國際宣傳與招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '09','has_admin' => true,'username' => '2017ntou09','organization' => '國際學生事務組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '10','has_admin' => true,'username' => '2017ntpu10','organization' => '教務處綜合業務組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '11','has_admin' => true,'username' => '2017nctu11','organization' => '教務處綜合組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '12','has_admin' => true,'username' => '2017nuk12','organization' => '教務處招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '13','has_admin' => true,'username' => '2017nccu13','organization' => '教務處綜合業務組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '14','has_admin' => true,'username' => '2017niu14','organization' => '國際事務中心','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '15','has_admin' => true,'username' => '2017ncu15','organization' => '教務處招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '16','has_admin' => true,'username' => '2017nuu16','organization' => '綜合業務組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '17','has_admin' => true,'username' => '2017nthu17','organization' => '教務處招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '18','has_admin' => true,'username' => '2017nutn18','organization' => '教務處企劃組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '19','has_admin' => true,'username' => '2017nsysu19','organization' => '教務處招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '20','has_admin' => true,'username' => '2017nttu20','organization' => '教務處綜合業務組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '21','has_admin' => true,'username' => '2017ym21','organization' => '綜合業務組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '22','has_admin' => true,'username' => '2017ndmctsgh22','organization' => '教務處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '23','has_admin' => true,'username' => '2017ncue23','organization' => '教務處教學資源組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '24','has_admin' => true,'username' => '2017npue24','organization' => '教務處綜合業務組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '25','has_admin' => true,'username' => '2017tmue25','organization' => '教務處招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '26','has_admin' => true,'username' => '2017ntcu26','organization' => '國際及兩岸事務暨研究發展處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '27','has_admin' => true,'username' => '2017nknu27','organization' => '教務處註冊組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '28','has_admin' => true,'username' => '2017ntue28','organization' => '教務處註冊組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '29','has_admin' => true,'username' => '2017nhcue29','organization' => '註冊組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '30','has_admin' => true,'username' => '2017ntupes30','organization' => '招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '31','has_admin' => true,'username' => '2017tpec31','organization' => '教務處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '32','has_admin' => true,'username' => '2017ntsu32','organization' => '教務處註冊組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '33','has_admin' => true,'username' => '2017tnua33','organization' => '教務處招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '34','has_admin' => true,'username' => '2017ntua34','organization' => '教務處綜合業務組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '35','has_admin' => true,'username' => '2017tnnua35','organization' => '教務處註冊組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '36','has_admin' => true,'username' => '2017pccu36','organization' => '教務處招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '37','has_admin' => true,'username' => '2017tku37','organization' => '招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '38','has_admin' => true,'username' => '2017mcu38','organization' => '教務處綜合業務組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '39','has_admin' => true,'username' => '2017thu39','organization' => '招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '40','has_admin' => true,'username' => '2017usc40','organization' => '教務處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '41','has_admin' => true,'username' => '2017isu41','organization' => '招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '42','has_admin' => true,'username' => '2017pu42','organization' => '國際暨兩岸事務處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '43','has_admin' => true,'username' => '2017au43','organization' => '招生中心','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '44','has_admin' => true,'username' => '2017fcu44','organization' => '招生行政組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '45','has_admin' => true,'username' => '2017fju45','organization' => '教務處招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '46','has_admin' => true,'username' => '2017cjcu46','organization' => '入學服務處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '47','has_admin' => true,'username' => '2017asia47','organization' => '國際學院','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '48','has_admin' => true,'username' => '2017shu48','organization' => '教務處招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '49','has_admin' => true,'username' => '2017dyu49','organization' => '國際暨兩岸交流處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '50','has_admin' => true,'username' => '2017chu50','organization' => '教務處 註冊組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '51','has_admin' => true,'username' => '2017tsu51','organization' => '國際及兩岸事務處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '52','has_admin' => true,'username' => '2017ukn52','organization' => '教務處招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '53','has_admin' => true,'username' => '2017ctbc53','organization' => '教務處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '54','has_admin' => true,'username' => '2017mdu54','organization' => '國際事務處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '55','has_admin' => true,'username' => '2017scu55','organization' => '招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '56','has_admin' => true,'username' => '2017knu56','organization' => '招生事務處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '57','has_admin' => true,'username' => '2017yzu57','organization' => '教務處註冊組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '58','has_admin' => true,'username' => '2017toko58','organization' => '招生處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '59','has_admin' => true,'username' => '2017hcu59','organization' => '招生服務處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '60','has_admin' => true,'username' => '2017nhu60','organization' => '國際及兩岸交流處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '61','has_admin' => true,'username' => '2017cycu61','organization' => '國際暨兩岸教育處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '62','has_admin' => true,'username' => '2017hfu62','organization' => '教務處招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '63','has_admin' => true,'username' => '2017ttu63','organization' => '註冊組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '64','has_admin' => true,'username' => '2017fgu64','organization' => '國際暨兩岸事務處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '65','has_admin' => true,'username' => '2017cgu65','organization' => '教務處招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '66','has_admin' => true,'username' => '2017csmu66','organization' => '教務處招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '67','has_admin' => true,'username' => '2017kmu67','organization' => '教務處 招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '68','has_admin' => true,'username' => '2017cmu68','organization' => '公共事務處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '69','has_admin' => true,'username' => '2017tmu69','organization' => '教務處招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '70','has_admin' => true,'username' => '2017tcu70','organization' => '教務處註冊組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '71','has_admin' => true,'username' => '2017ntust71','organization' => '教務處註冊組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '72','has_admin' => true,'username' => '2017yuntech72','organization' => '教務處綜合業務組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '73','has_admin' => true,'username' => '2017ntut73','organization' => '國際事務處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '74','has_admin' => true,'username' => '2017npust74','organization' => '綜合業務組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '75','has_admin' => true,'username' => '2017nkfust75','organization' => '國際處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '76','has_admin' => true,'username' => '2017kuas76','organization' => '招生業務組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '77','has_admin' => true,'username' => '2017nkmu77','organization' => '研究發展處國際事務組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '78','has_admin' => true,'username' => '2017nfu78','organization' => '綜合教務組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '79','has_admin' => true,'username' => '2017npic79','organization' => '招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '80','has_admin' => true,'username' => '2017nqu80','organization' => '研發處國際暨兩岸事務中心','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '81','has_admin' => true,'username' => '2017ncut81','organization' => '教務處綜合業務組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '82','has_admin' => true,'username' => '2017nutc82','organization' => '國際事務處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '83','has_admin' => true,'username' => '2017nkuht83','organization' => '教務處綜合業務組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '84','has_admin' => true,'username' => '2017ntub84','organization' => '教務處企劃組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '85','has_admin' => true,'username' => '2017ntunhs85','organization' => '研發處國際暨兩岸教育中心','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '86','has_admin' => true,'username' => '2017cyut86','organization' => '教務處招生服務中心','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '87','has_admin' => true,'username' => '2017stust87','organization' => '教務處綜合業務組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '88','has_admin' => true,'username' => '2017ksu88','organization' => '教務處綜合業務組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '89','has_admin' => true,'username' => '2017stu89','organization' => '教務處教務組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '90','has_admin' => true,'username' => '2017cnu90','organization' => '教務處招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '91','has_admin' => true,'username' => '2017must91','organization' => '國際交流中心','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '92','has_admin' => true,'username' => '2017fy92','organization' => '教務處招生暨入學服務中心','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '93','has_admin' => true,'username' => '2017hk93','organization' => '國際暨兩岸事務處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '94','has_admin' => true,'username' => '2017csu94','organization' => '國際事務處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '95','has_admin' => true,'username' => '2017uch95','organization' => '招生處試務組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '96','has_admin' => true,'username' => '2017vnu96','organization' => '教務處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '97','has_admin' => true,'username' => '2017mcut97','organization' => '註冊組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '98','has_admin' => true,'username' => '2017cute98','organization' => '教務行政組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => '99','has_admin' => true,'username' => '2017tajen99','organization' => '國際暨兩岸事務處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'A0','has_admin' => true,'username' => '2017kyuA0','organization' => '研發處國際交流中心','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'A1','has_admin' => true,'username' => '2017ltuA1','organization' => '教務處註冊組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'A2','has_admin' => true,'username' => '2017sjuA2','organization' => '國際學術交流中心','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'A3','has_admin' => true,'username' => '2017ctustA3','organization' => '招生及國際合作中心','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'A4','has_admin' => true,'username' => '2017tutA4','organization' => '招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'A5','has_admin' => true,'username' => '2017feuA5','organization' => '教務處註冊組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'A6','has_admin' => true,'username' => '2017ypuA6','organization' => '教務處註冊組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'A7','has_admin' => true,'username' => '2017ccutA7','organization' => '招生事務中心','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'A8','has_admin' => true,'username' => '2017nkutA8','organization' => '秘書室國際交流暨兩岸事務中心','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'A9','has_admin' => true,'username' => '2017custA9','organization' => '教務處註冊組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'B0','has_admin' => true,'username' => '2017tustB0','organization' => '國際交流中心','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'B1','has_admin' => true,'username' => '2017dahanB1','organization' => '教務處招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'B2','has_admin' => true,'username' => '2017wzuB2','organization' => '國際暨兩岸合作處境外學生事務組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'B3','has_admin' => true,'username' => '2017justB3','organization' => '教務處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'B4','has_admin' => true,'username' => '2017tcustB4','organization' => '教務處招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'B5','has_admin' => true,'username' => '2017ytitB5','organization' => '國際事務中心','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'B6','has_admin' => true,'username' => '2017fotechB6','organization' => '教務處招生中心','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'B7','has_admin' => true,'username' => '2017oitB7','organization' => '教務處註冊組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'B8','has_admin' => true,'username' => '2017tpcuB8','organization' => '國際交流中心','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'B9','has_admin' => true,'username' => '2017nanyaB9','organization' => '教務處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'C0','has_admin' => true,'username' => '2017wfuC0','organization' => '國際暨兩岸事務中心','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'C1','has_admin' => true,'username' => '2017tnuC1','organization' => '國際交流中心','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'C2','has_admin' => true,'username' => '2017ocuC2','organization' => '教務處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'C3','has_admin' => true,'username' => '2017chihleeC3','organization' => '國際暨兩岸交流處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'C4','has_admin' => true,'username' => '2017hwuC4','organization' => '教務處註冊組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'C5','has_admin' => true,'username' => '2017takmingC5','organization' => '教務處綜合業務組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'C6','has_admin' => true,'username' => '2017twuC6','organization' => '國際暨兩岸事務處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'C7','has_admin' => true,'username' => '2017meihoC7','organization' => '國際及兩岸交流處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'C8','has_admin' => true,'username' => '2017dlitC8','organization' => '教務處註冊組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'C9','has_admin' => true,'username' => '2017njuC9','organization' => '招生處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'D0','has_admin' => true,'username' => '2017tfD0','organization' => '研究發展處國際暨兩岸交流組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'D1','has_admin' => true,'username' => '2017hustD1','organization' => '招生服務中心','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'D2','has_admin' => true,'username' => '2017ckuD2','organization' => '研發處國際合作暨兩岸交流組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'D3','has_admin' => true,'username' => '2017hwhD3','organization' => '研發處國際交流中心','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'D4','has_admin' => true,'username' => '2017thtD4','organization' => '招生事務中心','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'D5','has_admin' => true,'username' => '2017tcmtD5','organization' => '招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'D6','has_admin' => true,'username' => '2017dilaD6','organization' => '教務組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'D7','has_admin' => true,'username' => '2017npuD7','organization' => '教務處註冊組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'D8','has_admin' => true,'username' => '2017lhuD8','organization' => '國際暨兩岸合作處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'D9','has_admin' => true,'username' => '2017ctuD9','organization' => '國際合作與交流處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'E0','has_admin' => true,'username' => '2017utaipeiE0','organization' => '教務處招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'E1','has_admin' => true,'username' => '2017hwaiE1','organization' => '國際交流組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'E2','has_admin' => true,'username' => '2017yduE2','organization' => '國際合作處國際與兩岸合作交流中心','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'E3','has_admin' => true,'username' => '2017fitE3','organization' => '教務處註冊課務組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'E4','has_admin' => true,'username' => '2017litE4','organization' => '招生中心','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'E5','has_admin' => true,'username' => '2017cgustE5','organization' => '教務處註冊組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'E6','has_admin' => true,'username' => '2017citE6','organization' => '國際暨兩岸事務處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'E7','has_admin' => true,'username' => '2017ttcE7','organization' => '學生發展處招生中心','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'E8','has_admin' => true,'username' => '2017apicE8','organization' => '永續發展處招生中心','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'E9','has_admin' => true,'username' => '2017kfcdcE9','organization' => '教務處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'F0','has_admin' => true,'username' => '2017nptuF0','organization' => '國際事務處-國際學生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'F1','has_admin' => true,'username' => '2017mmcF1','organization' => '教務處招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'F2','has_admin' => true,'username' => '2017tcpaF2','organization' => '教務處註冊組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'F3','has_admin' => true,'username' => '2017tbtsF3','organization' => '祕書暨公關室','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'F4','has_admin' => true,'username' => '2017cctF4','organization' => '教務處註冊組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'F5','has_admin' => true,'username' => '2017iktcF5','organization' => '教務處','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'F6','has_admin' => true,'username' => '2017iktcdsF6','organization' => '請輸入學校負責僑生事務的承辦單位名稱','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'F7','has_admin' => true,'username' => '2017tgstF7','organization' => '請輸入學校負責僑生事務的承辦單位名稱','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
            ['school_code' => 'FF','has_admin' => true,'username' => '2017nupsFF','organization' => '僑先部招生組','created_at' => Carbon::now()->toIso8601String(),'updated_at' => Carbon::now()->toIso8601String()],
        ]);
    }
}
